### ISSUE TITLE
[Bug]: GC overhead limit exceeded when list large number of oss objects

### ISSUE THREAD

**Issue by uncleGen** [aliyun/aliyun-emapreduce-sdk#110]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded 
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:87) 
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:195) 
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68) 
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:96) 
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:60) 
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:68) 
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:89) 
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:195) 
	at com.google.gson.Gson.toJson(Gson.java:593) 
	at com.google.gson.Gson.toJson(Gson.java:572) 
	at com.google.gson.Gson.toJson(Gson.java:527) 
	at com.google.gson.Gson.toJson(Gson.java:507) 
	at com.aliyun.fs.oss.utils.OSSClientAgent.listObjects(OSSClientAgent.java:204) 
	at com.aliyun.fs.oss.nat.JetOssNativeFileSystemStore.list(JetOssNativeFileSystemStore.java:369) 
	at com.aliyun.fs.oss.nat.JetOssNativeFileSystemStore.list(JetOssNativeFileSystemStore.java:358) 
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.lang.reflect.Method.invoke(Method.java:606) 
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187) 
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102) 
	at com.sun.proxy.$Proxy4.list(Unknown Source) 
	at com.aliyun.fs.oss.nat.NativeOssFileSystem.listStatus(NativeOssFileSystem.java:375) 
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1485) 
	at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1525) 
	at org.apache.hadoop.fs.FileSystem$4.<init>(FileSystem.java:1682) 
	at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1681) 
	at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1664) 
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:341) 
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:346) 
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:346) 
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:346) 
	at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.addInputPathRecursively(FileInputFormat.java:346)

**Comment by uncleGen** [comment]
worksfome and won't fix
