### ISSUE TITLE
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body

### ISSUE THREAD

**Issue by uncleGen** [aliyun/aliyun-emapreduce-sdk#121]
Error: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 24368795; received: 8317227
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:180)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at com.aliyun.oss.event.ProgressInputStream.read(ProgressInputStream.java:116)
        at com.aliyun.fs.oss.nat.NativeOssFileSystem$NativeOssFsInputStream.read(NativeOssFileSystem.java:74)

**Comment by potterlee-W** [comment]
did u fix it?
