### ISSUE TITLE
java.lang.IllegalArgumentException: Path must be absolute: null/part-00009

### ISSUE THREAD

**Issue by uncleGen** [aliyun/aliyun-emapreduce-sdk#124]
java.lang.IllegalArgumentException: Path must be absolute: null/part-00009
   at com.aliyun.fs.oss.nat.NativeOssFileSystem.pathToKey(NativeOssFileSystem.java:221)
   at com.aliyun.fs.oss.nat.JetOssNativeFileSystemStore.storeFile(JetOssNativeFileSystemStore.java:256)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:606)
   at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
   at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
   at com.sun.proxy.$Proxy15.storeFile(Unknown Source)
   at com.aliyun.fs.oss.nat.NativeOssFileSystem$NativeOssFsOutputStream.close(NativeOssFileSystem.java:146)

**Comment by uncleGen** [comment]
invalid and won’t fix
