### ISSUE TITLE
java.lang.NumberFormatException: multiple points

### ISSUE THREAD

**Issue by uncleGen** [aliyun/aliyun-emapreduce-sdk#178]
py4j.protocol.Py4JJavaError: An error occurred while calling o27.saveToTable.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 15 in stage 1.0 failed 1 times, most recent failure: Lost task 15.0 in stage 1.0 (TID 35, localhost): java.lang.NumberFormatException: multiple points
  at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1890)
  at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
  at java.lang.Double.parseDouble(Double.java:538)
  at java.text.DigitList.getDouble(DigitList.java:169)
  at java.text.DecimalFormat.parse(DecimalFormat.java:2056)
  at java.text.SimpleDateFormat.subParse(SimpleDateFormat.java:1869)
  at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1514)
  at java.text.DateFormat.parse(DateFormat.java:364)
  at org.apache.spark.aliyun.odps.PythonOdpsAPI$$anonfun$org$apache$spark$aliyun$odps$PythonOdpsAPI$$writeTransfer$2.apply(PythonOdpsAPI.scala:146)
  at org.apache.spark.aliyun.odps.PythonOdpsAPI$$anonfun$org$apache$spark$aliyun$odps$PythonOdpsAPI$$writeTransfer$2.apply(PythonOdpsAPI.scala:136)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at org.apache.spark.aliyun.odps.PythonOdpsAPI.org$apache$spark$aliyun$odps$PythonOdpsAPI$$writeTransfer(PythonOdpsAPI.scala:136)

**Comment by uncleGen** [comment]
SimpleDateFormat maybe not thread-safe. Let me fix it.
