### ISSUE TITLE
format("org.apache.spark.aliyun.odps.datasource")：Unsupported type 'STRUCT'

### ISSUE THREAD

**Issue by BourneYu** [aliyun/aliyun-emapreduce-sdk#336]
**Describe the bug**
java.sql.SQLException: Unsupported type 'STRUCT'
  at org.apache.spark.aliyun.utils.OdpsUtils.getCatalystType(OdpsUtils.scala:340)
  at org.apache.spark.aliyun.odps.datasource.ODPSRelation$$anonfun$1.apply(ODPSRelation.scala:56)
  at org.apache.spark.aliyun.odps.datasource.ODPSRelation$$anonfun$1.apply(ODPSRelation.scala:56)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)

**Additional context**
v1.6.0

how to solve this problem？

**Comment by uncleGen** [comment]
`STRUCT ` `ARRAY` and `MAP` are still not supported.
