### ISSUE TITLE
Can't load this .dll (machine code=0xe800) on a AMD 64-bit platform

### ISSUE THREAD

**Issue by kingreatwill** [aliyun/aliyun-emapreduce-sdk#459]
win10
spark3.0

code
```
import os

from pyspark import SparkContext, SparkConf

os.environ[
    'PYSPARK_SUBMIT_ARGS'] = '--packages com.aliyun.emr:emr-ons_2.11:2.0.0 pyspark-shell'

conf = SparkConf()
conf.set("appName", "OSS_Demo")
conf.set("fs.oss.impl", "com.aliyun.emr.fs.oss.JindoOssFileSystem")
sc = SparkContext(conf=conf)

rdd = sc.textFile("oss://xx:xxx@xx.xx/hadoop/data.txt")
rdd.collect()
```
error
```
java.lang.UnsatisfiedLinkError: C:\Users\xx\AppData\Local\Temp\libjboot-ed376a31ece9bc6a_20200623_141838.so: Can't load this .dll (machine code=0xe800) on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.alibaba.jboot.NativeCodeLoader.loadLibrary(NativeCodeLoader.java:78)
	at com.alibaba.jboot.NativeCodeLoader.load(NativeCodeLoader.java:41)
	at com.alibaba.jboot.JbootNative.<clinit>(JbootNative.java:13)
	at com.aliyun.emr.fs.common.AbstractJindoFileSystem.initialize(AbstractJindoFileSystem.java:108)
	at com.aliyun.emr.fs.oss.JindoOssFileSystem.initialize(JindoOssFileSystem.java:68)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
	at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:268)
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:239)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:325)
```

**Comment by uncleGen** [comment]
`JindoOssFileSystem` is the OSS FS implementation from EMR. So, submit a work order request in Aliyun please.

**Comment by kingreatwill** [comment]
![image](https://user-images.githubusercontent.com/13087689/89017876-912fe880-d34d-11ea-9280-ac3fe2b84703.png)

**Comment by uncleGen** [comment]
cc @drankye

**Comment by wsu13** [comment]
Sorry I didn't make it clear in the Chinese Doc. I Just upload an [English doc](https://github.com/aliyun/aliyun-emapreduce-sdk/blob/master-2.x/docs/jindofs_sdk_how_to_en.md).  The error is expected. Currently, JindoFS SDK only supports Linux and MacOS operating systems.

**Comment by kingreatwill** [comment]
@wsu13 OK, I Know.
